.\" Manpage for node_search.py.
.\" Contact ckankel@nd.edu to correct typos or errors.
.TH man 1 "15 SEPT 2017" "1.1.0" "node_search man page"
.SH NAME
node_search \- get node, user, or host-group information from Univa Grid Engine
.SH SYNOPSIS
\fBnode_search.sh \fR[\fB-h\fR, \fB--help\fR] [\fB-d\fR, \fB--debug\fR] [\fB-a\fR, \fB--all\fR] 
[\fB-g\fR, \fB--general_access\fR] [\fB-H\fR, \fB --hosts\fR] [\fB-hostname\fR] 
[\fB-u\fR, \fB--user username\fR] [\fB-uf username\fR] [\fB-U\fR] [\fB-v\fR, \fB--visual\fR]

.SH DESCRIPTION
\fRnode_search gathers information from the Univa Grid Engine and displays that information to 
stdout, which can then be redirected as desired. The following information can be obtained:
." Next Paragraph
.PP
\fRQueue/Host-group core usage, User Job information, which Host-groups a User belongs to, which 
Host-groups exist, which users are recognized by UGE currently.

." BEGIN OPTIONS !!

.SH OPTIONS
.TP
\fB-h\fR, \fB--help 
\fRShow a small help dialogue with a short description of each option and a few examples.

." Next Option . . .
.TP
\fB-d\fR, \fB--debug 
\fRDisplay information pertaining to the Debug queue such as core usage (free cores, disabled cores, 
used cores) and node usage (free nodes, disabled nodes, used nodes). This option allows the optional
\fB--details \fRflag or it can take the \fB-v\fR/\fB--visual \fRflag.

." Next Option . . .
.TP
\fB-g\fR, \fB--general_access
\fRDisplay information pertaining to the Long(General Access) queue such as core usage (free cores, 
disabled cores, used cores) and node usage (free nodes, disabled nodes, used nodes). This option 
allows the optional \fB--details \fRflag or it can take the \fB-v\fR/\fB--visual\fR flag.

." Next Option . . .
.TP
\fB-H\fR, \fB--hosts
\fRShows all known hosts configured to be used by the Univa Grid Engine. \fINot all of the host-groups 
may be available to you, see \fB-uf

." Next Option . . .
.TP
\fB-[hostname]
\fRThis option takes in a variable hostname, which can be found by using \fB-H\fR, and gives the 
same information found by using \fB-d \fRor \fB-g \fRi.e. core usage and node usage information 
can be found and displayed from that specified hostname. Even if you cannot submit jobs to this 
specific host-group, you can still view this information. Don't get confused. \fBNOTE:\fR You 
do not need the \fB"@"\fR while specifying the hostname. (i.e. -corke not -@corke)

." Next Option . . .
.TP
\fB-a\fR,\fB --all
\fRDisplay usage information on all nodes detected by UGE. This searches every host-group with a 
running total of usage, while discarding any duplicate machines. Duplicate machines occur when 
there are nested hostgroups. The \fB--details\fR option can be used with this as well.

." Next Option . . .
.TP
\fB-u\fR, \fB--user \fR[\fBusername\fR]
\fRDisplay job information along with what node and core information pertaining to the specifed 
user after \fB-u \fRor \fB--user\fR. The maximum Memory used detected by the grid engine will also
be shown. This option will take the optional flag \fB-details\fR for a more detailed output. The 
detailed output will display all of the jobs running on the nodes that the specified user has jobs 
running on. Since our nodes are a shared resource, it may be useful to see this if a job is running 
poorly.

." Next Option . . .
.TP
\fB-uf \fR[\fBusername\fR]
\fRShow which host-groups and user-lists the specified user after \fB-uf \fRbelongs to. The 
information displayed will indicate which host-groups the user has access to, i.e. which host-groups 
that user can submit jobs to using the UGE. The user-list aspect of this option is not entirely 
useful, but those user-lists are what is used in conifguring qconf to tell the UGE which users belong 
to which host-groups.

." Next Option . . .
.TP
\fB-U
\fRDifferent from \fB-u\fR, \fB-U \fRwill display all users currently interacting with the UGE. This 
means those users: have jobs running somewhere controlled by the UGE, are waiting in a queue controlled 
by the UGE, or recently interacted with the UGE in some way. Thus, not every user who has access to 
the UGE will be displayed from this. Do not fret if your name is not on this list. 

.SH OPTIONAL FLAGS

.TP
\fB-v\fR, \fB--visual
\fRDisplay a visual representation of a queue. In this visual representation, \fB[0]\fR represents 
an open core, \fB[#]\fR represents a disabled core, and \fB[~]\fR represents a used or taken core. 
This flag can be passed in after using \fBnode_search.py -d, -g, \fRor \fB-[hostname]\fR. See 
Examples below.

." Next Option . . .
.TP
\fB--details
\fRShow a more detailed output of whatever was passed into \fRnode_search\fR. The result of 
\fB--details\fR depends on what it is modifying. If it is modifying the debug queue, long queue, or a 
specifed host-group, then the output will show all of the machines/nodes that belong to that queue 
or host-group. Each one of those nodes will also show its core  usage (used vs total). This will be
the same behavior that occurs if \fB--details\fR is used to modify \fB-a \fR or\fB --all\fR. If \fB--details
\fRis modifying a user, then all of the nodes the specified user is running will be displayed along with all
of the processes that user owns and the respective memory usage, CPU%, and run time of each process. This is
useful for when a job submitted through UGE spawns or starts multiple processes which are not necessarily tracked
by UGE.  If the user has any pending jobs then those will be shown as well. If \fB--details \fRis modifying the
\fB-uf \fRoption, then it will display all of the nodes which belong to the host-groups the specified user has access to.

." END OPTIONS !!

.SH EXAMPLES

.TP
\fBnode_search.py -g
\fRDisplay information pertaining to the long queue (general access)

.TP
\fBnode_search.py --debug --details
\fRDisplay detailed information pertaining to the debug queue, this will yield information such as 
the name of all of the nodes currently occupying the debug queue and their core information.

.TP
\fBnode_search.py -general_access -v
\fRDisplay a visual representation of the host-group '@general_access'. Notice how the '@' is not 
needed for the host-group.

.TP
\fBnode_search.py -uf JohnDoe33 --details
\fRDisplay a detailed view of the host-groups that user JohnDoe33 belongs to. This will show each 
and every node that also belongs to those host-groups. It may be wise to pipe this output through 
something along the lines of less/more. e.g. node_search.py -uf JohnDoe33 --details | less

.TP
\fBnode_search.py -u JohnDoe
\fRDisplay the user JohnDoe and their jobs along with core usage and the nodes the jobs are running
on. Will display total memory usage per node as used by user JohnDoe.

 
.SH BUGS
\fRNo known bugs at the current moment in time.
Report any new findings to ckankel@nd.edu.
.SH AUTHOR
\fRCody Kankel (ckankel@nd.edu)
